version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  whoami:
    image: containous/whoami
    labels:
      caddy: http://whoami.localhost https://whoami.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
  uvicorn:
    build: ./
    ports:
      - 8000:8000
    command: uvicorn app:app  --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'
    labels:
      caddy: http://uvicorn.localhost https://uvicorn.localhost
      caddy.reverse_proxy: "{{upstreams 8000}}"
  quart-raw:
    build: ./
    ports:
      - 5000:5000
    command: python app.py
    labels:
      #Force https for the raw test
      caddy: http://quart.localhost https://quart.localhost
      caddy.reverse_proxy: "{{upstreams 5000}}"


networks:
  caddy: {}

volumes:
  caddy_data: {}

